### ISSUE TITLE
Modify github actions workflow to trigger on both push and pull

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelapi#58]
Will ensure that code coverage computation by Coveralls happens both when a PR is opened _and_ when it is merged (so that the `main` branch coverage is always up to date).

With this change, the `workflow_dispatch` event trigger can probably be dropped.

**Comment by rmanaem** [comment]
I'd like us to have the best of both worlds:

- Avoid running the workflow twice during PRs, see #42 
- `main` branch coverage is updated when a PR is merged

Since every merged PR to `main` results in a push we could modify the workflow to
```
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
```
